### ISSUE TITLE
init impl task list

### ISSUE THREAD

**Issue by unship** [openmessaging/openmessaging-go#2]
relate https://github.com/openmessaging/openmessaging-go/issues/1

# MessagingAccessPoint: "dynamic" vs "static"

[cpp impl](https://github.com/openmessaging/openmessaging-cpp/blob/master/OMS.h#L56) use `dlopen`, and [java impl](https://github.com/openmessaging/openmessaging-java/blob/master/openmessaging-api/src/main/java/io/openmessaging/internal/MessagingAccessPointAdapter.java#L56) use `Class.forName` for load `MessagingAccessPoint lib`, go can use [plugin](https://golang.org/pkg/plugin) to load lib， but it is not common in go community, So I recommend use [golang's sql impl style](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L41-L54) 
 

# package management
- go mod（recommend）
- dep

# return err instead of `throws`

do not panic, return err

# OMSResponseStatus code generator

for now, hard code this part

# TODO

- [ ] OMS URL parser
- [ ] MessagingAccessPoint, ResourceManager
- [ ] OMS
- [ ] OMSResponseStatus
- [ ] Consumer
- [ ] Producer
- [ ] ProducerInterceptor
- [ ] ConsumerInterceptor
- [ ] ~~rocketmq MessagingAccessPoint impl~~
- [ ] ~~kafka MessagingAccessPoint impl~~
- [ ] ~~pulsar MessagingAccessPoint impl~~

**Comment by duhengforever** [comment]
@llvim For rocketmq/kafka/pulsar  MessagingAccessPoint impl, We can put it into other projects for implementation. Currently, this project only focuses on interface.
